#!/bin/bash

set -Eeuxo pipefail

git clone https://gitlab.winehq.org/wine/wine.git wine-source
cd wine-source

echo "Building $(git log -1)"
echo "---"

./tools/make_requests
./tools/make_makefiles
autoreconf -f

mkdir -p build64
cd build64
../configure -q -C --enable-win64 --enable-werror --with-mingw
make -s -j$(nproc)
cd ..

mkdir -p build32
cd build32
../configure -q -C --enable-werror --with-mingw
make -s -j$(nproc)
cd ..

export BASEDIR=/home/vagrant/winebuild/
mkdir -p $BASEDIR

if ! test -s .git/rebase-merge/git-rebase-todo
then
    make -s -j$(nproc) -C build32 install-lib install-test DESTDIR=$BASEDIR
    make -s -j$(nproc) -C build64 install-lib install-test DESTDIR=$BASEDIR
fi

# git reset --hard
